export const restaurantsData = {
  restaurants: [
  {
    id: "r1",
    name: "Bella Italia",
    cuisine: ["Italian", "Pizza", "Pasta"],
    rating: 4.5,
    reviewsCount: 128,
    deliveryTime: "30-40 min",
    deliveryFee: 2.99,
    distance: "1.8 km",
    priceLevel: "$$",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
    bannerImage: "https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=1200",
    tags: ["Popular", "Fast delivery", "Top rated"],
    description: "Authentic Italian cuisine with fresh ingredients and rich flavors.",
    menuItems: [
      {
        id: "m1",
        name: "Margherita Pizza",
        description: "Tomato sauce, mozzarella, basil",
        price: 12.99,
        category: "Pizza",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
      },
      {
        id: "m2",
        name: "Pasta Carbonara",
        description: "Creamy sauce with pancetta and parmesan",
        price: 11.49,
        category: "Pasta",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
      },
      {
        id: "m3",
        name: "Bruschetta",
        description: "Toasted bread with tomato and olive oil",
        price: 6.99,
        category: "Starter",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800",
      },
      {
        id: "m13",
        name: "Pepperoni Pizza",
        description: "Pepperoni, mozzarella, tomato sauce",
        price: 14.99,
        category: "Pizza",
        isVeg: false,
        spicyLevel: 1,
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800",
      },
      {
        id: "m14",
        name: "Four Cheese Pizza",
        description: "Mozzarella, cheddar, parmesan, blue cheese",
        price: 15.49,
        category: "Pizza",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?w=800",
      },
      {
        id: "m15",
        name: "Lasagna",
        description: "Layers of pasta, meat sauce, ricotta cheese",
        price: 13.49,
        category: "Pasta",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1619895092538-128341789043?w=800",
      },
      {
        id: "m16",
        name: "Fettuccine Alfredo",
        description: "Creamy alfredo sauce with parmesan",
        price: 12.49,
        category: "Pasta",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800",
      },
      {
        id: "m17",
        name: "Caesar Salad",
        description: "Romaine lettuce, parmesan, croutons",
        price: 7.99,
        category: "Salad",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800",
      },
      {
        id: "m18",
        name: "Tiramisu",
        description: "Classic Italian coffee-flavored dessert",
        price: 5.99,
        category: "Dessert",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
      },
      {
        id: "m19",
        name: "Minestrone Soup",
        description: "Italian vegetable soup with beans and pasta",
        price: 6.49,
        category: "Soup",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
      },
    ],
  },
  {
    id: "r2",
    name: "Burger Town",
    cuisine: ["Burgers", "Fast Food"],
    rating: 4.3,
    reviewsCount: 94,
    deliveryTime: "20-30 min",
    deliveryFee: 1.99,
    distance: "2.3 km",
    priceLevel: "$",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    bannerImage: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200",
    tags: ["Best seller", "Budget friendly"],
    description: "Juicy burgers, crispy fries, and quick service.",
    menuItems: [
      {
        id: "m4",
        name: "Classic Burger",
        description: "Beef patty, lettuce, tomato, cheese",
        price: 8.99,
        category: "Burger",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
      },
      {
        id: "m6",
        name: "French Fries",
        description: "Crispy salted fries",
        price: 3.49,
        category: "Sides",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800",
      },
      {
        id: "m21",
        name: "Cheese Burst Burger",
        description: "Double patty with molten cheese filling",
        price: 10.49,
        category: "Burger",
        isVeg: false,
        spicyLevel: 1,
        image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800",
      },
      {
        id: "m22",
        name: "Veggie Burger",
        description: "Veg patty, lettuce, tomato, special sauce",
        price: 7.49,
        category: "Burger",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=800",
      },
      {
        id: "m23",
        name: "Onion Rings",
        description: "Golden fried onion rings",
        price: 4.29,
        category: "Sides",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=800",
      },
      {
        id: "m24",
        name: "Chicken Nuggets",
        description: "Crispy chicken bites with dip",
        price: 5.99,
        category: "Sides",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=800",
      },
      {
        id: "m25",
        name: "Chocolate Shake",
        description: "Creamy chocolate milkshake",
        price: 4.99,
        category: "Drinks",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
      },
      {
        id: "m26",
        name: "Spicy Chicken Burger",
        description: "Crispy chicken with spicy mayo",
        price: 8.49,
        category: "Burger",
        isVeg: false,
        spicyLevel: 3,
        image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
      },
    ],
  },
  {
    id: "r3",
    name: "Sushi House",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.6,
    reviewsCount: 76,
    deliveryTime: "25-35 min",
    deliveryFee: 3.49,
    distance: "3.1 km",
    priceLevel: "$$",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800",
    bannerImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200",
    tags: ["Fresh", "Premium", "Healthy"],
    description: "Fresh sushi rolls, bowls, and Japanese specialties.",
    menuItems: [
      {
        id: "m7",
        name: "Salmon Roll",
        description: "Fresh salmon, rice, nori",
        price: 13.99,
        category: "Roll",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800",
      },
      {
        id: "m8",
        name: "Veg Sushi Platter",
        description: "Avocado, cucumber, carrot rolls",
        price: 10.99,
        category: "Platter",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
      },
      {
        id: "m9",
        name: "Miso Soup",
        description: "Warm miso broth with tofu",
        price: 4.49,
        category: "Soup",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800",
      },
      {
        id: "m28",
        name: "Tuna Roll",
        description: "Tuna, rice, nori, sesame",
        price: 14.49,
        category: "Roll",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
      },
      {
        id: "m29",
        name: "Chicken Teriyaki Bowl",
        description: "Rice bowl with grilled chicken and teriyaki sauce",
        price: 12.99,
        category: "Bowl",
        isVeg: false,
        spicyLevel: 1,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800",
      },
      {
        id: "m30",
        name: "Edamame",
        description: "Lightly salted steamed soybeans",
        price: 5.49,
        category: "Starter",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c2?w=800",
      },
      {
        id: "m31",
        name: "Tempura Shrimp",
        description: "Crispy shrimp with dipping sauce",
        price: 9.99,
        category: "Starter",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1604908554049-4b5f7f04b1d1?w=800",
      },
      {
        id: "m32",
        name: "Avocado Roll",
        description: "Avocado, rice, nori",
        price: 9.49,
        category: "Roll",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
      },
      {
        id: "m33",
        name: "Green Tea Ice Cream",
        description: "Japanese matcha ice cream",
        price: 4.99,
        category: "Dessert",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=800",
      },
      {
        id: "m34",
        name: "Salmon Sashimi",
        description: "Fresh sliced salmon",
        price: 15.99,
        category: "Sashimi",
        isVeg: false,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800",
      },
    ],
  },
  {
    id: "r4",
    name: "Spice Hub",
    cuisine: ["Indian", "Biryani", "Curries"],
    rating: 4.2,
    reviewsCount: 211,
    deliveryTime: "20-30 min",
    deliveryFee: 1.49,
    distance: "1.1 km",
    priceLevel: "$",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800",
    bannerImage: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=1200",
    tags: ["Spicy", "Popular", "Local favorite"],
    description: "Rich Indian flavors with spicy curries and biryanis.",
    menuItems: [
      {
        id: "m10",
        name: "Chicken Biryani",
        description: "Fragrant basmati rice with chicken",
        price: 9.99,
        category: "Biryani",
        isVeg: false,
        spicyLevel: 3,
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      {
        id: "m11",
        name: "Paneer Butter Masala",
        description: "Creamy tomato gravy with paneer",
        price: 8.49,
        category: "Curry",
        isVeg: true,
        spicyLevel: 2,
        image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=800",
      },
      {
        id: "m12",
        name: "Garlic Naan",
        description: "Soft naan with garlic butter",
        price: 2.99,
        category: "Bread",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
      },
      {
        id: "m35",
        name: "Mutton Biryani",
        description: "Slow cooked mutton with fragrant rice",
        price: 11.99,
        category: "Biryani",
        isVeg: false,
        spicyLevel: 3,
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800",
      },
     
      {
        id: "m37",
        name: "Butter Chicken",
        description: "Creamy tomato chicken curry",
        price: 10.49,
        category: "Curry",
        isVeg: false,
        spicyLevel: 2,
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800",
      },
      {
        id: "m38",
        name: "Veg Thali",
        description: "Complete meal with curry, dal, rice, roti",
        price: 8.99,
        category: "Thali",
        isVeg: true,
        spicyLevel: 1,
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800",
      },
      {
        id: "m39",
        name: "Dal Tadka",
        description: "Yellow lentils tempered with spices",
        price: 6.49,
        category: "Curry",
        isVeg: true,
        spicyLevel: 1,
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
      },
      {
        id: "m40",
        name: "Raita",
        description: "Cooling yogurt with cucumber and spices",
        price: 2.49,
        category: "Side",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1752673508949-f4aeeaef75f0?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      {
        id: "m41",
        name: "Gulab Jamun",
        description: "Soft milk dumplings in sugar syrup",
        price: 3.99,
        category: "Dessert",
        isVeg: true,
        spicyLevel: 0,
        image: "https://images.unsplash.com/photo-1593701461250-d7b22dfd3a77?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
    ],
  },
],
  "categories": [
    {
      "id": "c1",
      "name": "Pizza",
      "icon": "pizza"
    },
    {
      "id": "c2",
      "name": "Burger",
      "icon": "hamburger"
    },
    {
      "id": "c3",
      "name": "Sushi",
      "icon": "fish"
    },
    {
      "id": "c4",
      "name": "Indian",
      "icon": "bowl-food"
    },
    {
      "id": "c5",
      "name": "Dessert",
      "icon": "ice-cream"
    }
  ],
  "cart": [
    {
      "id": "cart1",
      "restaurantId": "r1",
      "itemId": "m1",
      "name": "Margherita Pizza",
      "price": 12.99,
      "quantity": 1,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800"
    },
    {
      "id": "cart2",
      "restaurantId": "r1",
      "itemId": "m2",
      "name": "Pasta Carbonara",
      "price": 11.49,
      "quantity": 2,
      "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800"
    }
  ],
  "orders": [
    {
      "id": "o1",
      "orderNumber": "FD1201",
      "restaurantName": "Sushi House",
      "status": "Delivered",
      "itemsCount": 3,
      "total": 27.5,
      "date": "2026-05-10",
      "time": "2:30 PM"
    },
    {
      "id": "o2",
      "orderNumber": "FD1187",
      "restaurantName": "Bella Italia",
      "status": "Delivered",
      "itemsCount": 2,
      "total": 22.48,
      "date": "2026-05-08",
      "time": "7:15 PM"
    },
    {
      "id": "o3",
      "orderNumber": "FD1165",
      "restaurantName": "Spice Hub",
      "status": "On the way",
      "itemsCount": 2,
      "total": 19.9,
      "date": "2026-05-05",
      "time": "12:45 PM"
    }
  ],
  "user": {
    "id": "u1",
    "name": "John Doe",
    "email": "john.doe@example.com",
    "avatar": "https://i.pravatar.cc/150?img=12",
    "address": "221B Baker Street, London"
  }
}